services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-web
    restart: unless-stopped
    networks:
      - shared_net

networks:
  shared_net:
    external: true
